DROP TABLE IF EXISTS
    USERS,
    ROLES,
--     USERS_ROLES,
    RECYCLING_POINTS,
    WORKING_HOURS,
    RECYCLABLE_TYPES,
    RECYCLING_POINTS_RECYCLABLE_TYPES;

DROP TYPE IF EXISTS days_of_week;

CREATE TYPE days_of_week AS ENUM (
    'MONDAY',
    'TUESDAY',
    'WEDNESDAY',
    'THURSDAY',
    'FRIDAY',
    'SATURDAY',
    'SUNDAY'
    );

CREATE TABLE ROLES
(
    id   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    name varchar(20) UNIQUE                                  NOT NULL
);

INSERT INTO ROLES (name)
VALUES ('ROLE_SUPERADMIN'),
       ('ROLE_ADMIN'),
       ('ROLE_USER');

CREATE TABLE USERS
(
    id       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    username varchar(20) UNIQUE                                  NOT NULL,
    password varchar(20)                                         NOT NULL,
    email    varchar(50) UNIQUE,
    role_id  bigint REFERENCES ROLES (id) ON DELETE CASCADE      NOT NULL
);
-- todo пароли должны быть закодированы, как при создании нового пользователя
INSERT INTO USERS (username, password, email, role_id)
VALUES ('superadmin', 'superadmin', null, 1),
       ('admin', 'admin', null, 2);

CREATE TABLE RECYCLING_POINTS
(
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    name         varchar(100),
    address      varchar(100),
    phone_number varchar(30),
    website      varchar(100),
    latitude     numeric,
    longitude    numeric
);

CREATE TABLE WORKING_HOURS
(
    recycling_point_id bigint REFERENCES RECYCLING_POINTS (id) ON DELETE CASCADE,
--     day_of_week        days_of_week,
    day_of_week        smallint,
    opening_time       time,
    closing_time       time,
    lunch_start_time   time,
    lunch_end_time     time,
    PRIMARY KEY (recycling_point_id, day_of_week)
);

CREATE TABLE RECYCLABLE_TYPES
(
    id   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    name varchar(100) UNIQUE                                 NOT NULL
);

INSERT INTO RECYCLABLE_TYPES (name)
VALUES ('PLASTIC'),
       ('PAPER'),
       ('GLASS'),
       ('BULKY_WASTE'),
       ('APPLIANCES'),
       ('HAZARDOUS_WASTE'),
       ('METAL'),
       ('CLOTHES');

CREATE TABLE RECYCLING_POINTS_RECYCLABLE_TYPES
(
    recycling_point_id bigint REFERENCES RECYCLING_POINTS (id) ON DELETE CASCADE,
    recyclable_type_id bigint REFERENCES RECYCLABLE_TYPES (id) ON DELETE CASCADE,
    PRIMARY KEY (recycling_point_id, recyclable_type_id)
);